/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demo;

import java.awt.GridLayout;
import javax.swing.*;
import java.sql.*;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author wailff
 */
public class FormHabitaciones extends javax.swing.JFrame {
   private static final String USER="root";
   private static final String PASSWORD="";
   private static final String DB="jdbc:mysql://localhost:3307/hotel";
   DefaultTableModel model;
    /**
     * Creates new form FormHabitaciones
     */
    public FormHabitaciones() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProductos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txt_id_habitacion = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_ocupantes = new javax.swing.JTextField();
        btn_guardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("             DASHBOARD SALES");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        tableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "nombre", "ocupantes", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableProductos);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("                                      HABITACIONES");

        btn_guardar.setText("guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txt_id_habitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(txt_ocupantes, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 165, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_id_habitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ocupantes, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
       DefaultTableModel modelo=(DefaultTableModel)tableProductos.getModel();
       //modelo.addRow(new Object[]{txt_id_habitacion.getText(),txt_nombre.getText(),txt_ocupantes.getText()});
       FormHabitaciones form=new FormHabitaciones();
       String id=txt_id_habitacion.getText();
       String nombre=txt_nombre.getText();
       String ocupantes=txt_ocupantes.getText();
       Connection conn=null;
       try{
           conn=DriverManager.getConnection(DB,USER,PASSWORD);
           Statement statement=conn.createStatement();
           String query="insert into habitaciones values(0,'"+nombre+"','"+ocupantes+"')";
           statement.executeUpdate(query);
           form.getAll();
           modelo.fireTableDataChanged();
           txt_id_habitacion.setText("");
           txt_nombre.setText("");
           txt_ocupantes.setText("");
           JOptionPane.showMessageDialog(null,"insertado");
           
       }catch(SQLException e){
           
       }
      
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void tableProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProductosMouseClicked
        // TODO add your handling code here:
        int column=tableProductos.getColumnModel().getColumnIndexAtX(evt.getX());
        int row=evt.getY()/tableProductos.getRowHeight();
        if(row<tableProductos.getRowCount() && row>=0 && column<tableProductos.getColumnCount() && column>0){
            Object value=tableProductos.getValueAt(row,column);
            Object id_habitacion=tableProductos.getValueAt(row, 0);
            Object nombre=tableProductos.getValueAt(row, 1);
            Object ocupantes=tableProductos.getValueAt(row, 2);
            if(value instanceof JButton){
                ((JButton)value).doClick();
                JButton btn=(JButton) value;
                
                 if(btn.getName().equals("modificar")){
                    String[] items = {"One", "Two", "Three", "Four", "Five"};
                    //JComboBox<String> combo = new JComboBox<>(items);
                    JTextField field1 = new JTextField(""+nombre);
                    JTextField field2 = new JTextField(""+ocupantes);
                    JPanel panel = new JPanel(new GridLayout(0, 1));
                    //panel.add(combo);
                    panel.add(new JLabel("Nombre"));
                    panel.add(field1);
                    panel.add(new JLabel("Ocupantes"));
                    panel.add(field2);
                    int result = JOptionPane.showConfirmDialog(null, panel, "Modificar habitacion",
                        JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
                    if (result == JOptionPane.OK_OPTION) {
                        
                    } else {
                        System.out.println("Cancelled");
                    }
                 }
                 if(btn.getName().equals("eliminar")){
                       JOptionPane.showMessageDialog(null,"click en boton eliminar\n habitacion"+id_habitacion);
                 }
            }else{
                JOptionPane.showMessageDialog(null,"click en la tabla");
            }
        }
    }//GEN-LAST:event_tableProductosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FormHabitaciones form=new FormHabitaciones();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormHabitaciones form=new FormHabitaciones();
                form.getAll();
                form.setVisible(true);
            }
        });
    }
    public void getAll(){
      DefaultTableModel modelo=(DefaultTableModel)tableProductos.getModel();
      //se renderisa la tabla de habitaciones
      tableProductos.setDefaultRenderer(Object.class, new RenderTable());
      
      JButton btnEditar=new JButton("Modificar");
      btnEditar.setName("modificar");
      JButton btnEliminar=new JButton("Eliminar");
      btnEliminar.setName("eliminar");
      Connection conn=null;
       try{
           conn=DriverManager.getConnection(DB,USER,PASSWORD);
           Statement statement=conn.createStatement();
           String query="select *from habitaciones";
           ResultSet results = statement.executeQuery(query);
           ResultSetMetaData metaData = results.getMetaData();
           int columnCount = metaData.getColumnCount();
           while(results.next()){
               JButton btn_editar=new JButton("editar");
               modelo.addRow(new Object[]{results.getInt("id_habitacion"),results.getString("nombre"),results.getInt("ocupantes"),
                                                            btnEditar,btnEliminar
                                                          });
           }
          
       }catch(SQLException e){
           
       }
    }
    public void getHabitaciones(){
         Connection conn=null;
       try{
           conn=DriverManager.getConnection(DB,USER,PASSWORD);
           System.out.println("connected");
           Statement statement=conn.createStatement();
           String query="select *from habitaciones";
           ResultSet results = statement.executeQuery(query);
           JTable table = new JTable(buildTableModel(results));
           JOptionPane.showMessageDialog(null, new JScrollPane(table));
          
       }catch(SQLException e){
           
       }
    }
    public static DefaultTableModel buildTableModel(ResultSet results)throws SQLException{
        ResultSetMetaData metaData = results.getMetaData();

        // names of columns
        Vector<String> columnNames = new Vector<String>();
        int columnCount = metaData.getColumnCount();
        for (int column = 1; column <= columnCount; column++) {
            columnNames.add(metaData.getColumnName(column));
        }

        // data of the table
        Vector<Vector<Object>> data = new Vector<Vector<Object>>();
        while (results.next()) {
            Vector<Object> vector = new Vector<Object>();
            for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {
                vector.add(results.getObject(columnIndex));
            }
            data.add(vector);
        }

        return new DefaultTableModel(data, columnNames);
        
    }
    public void query(String query){
       Connection conn=null;
       try{
           conn=DriverManager.getConnection(DB,USER,PASSWORD);
           System.out.println("connected");
           Statement statement=conn.createStatement();
           ResultSet results = statement.executeQuery(query);
           while(results.next()){
               System.out.println(results.getString("nombre"));
           }
          
       }catch(SQLException e){
           
       }
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableProductos;
    private javax.swing.JTextField txt_id_habitacion;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_ocupantes;
    // End of variables declaration//GEN-END:variables
}
